/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RandomRouteImport } from './routes/random'
import { Route as RamailoRouteImport } from './routes/ramailo'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LevelRouteImport } from './routes/level'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminCdcRouteImport } from './routes/admin.cdc'

const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const RamailoRoute = RamailoRouteImport.update({
  id: '/ramailo',
  path: '/ramailo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelRoute = LevelRouteImport.update({
  id: '/level',
  path: '/level',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCdcRoute = AdminCdcRouteImport.update({
  id: '/admin/cdc',
  path: '/admin/cdc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/create': typeof CreateRoute
  '/learn': typeof LearnRoute
  '/level': typeof LevelRoute
  '/play': typeof PlayRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/ramailo': typeof RamailoRoute
  '/random': typeof RandomRoute
  '/reminders': typeof RemindersRoute
  '/admin/cdc': typeof AdminCdcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/create': typeof CreateRoute
  '/learn': typeof LearnRoute
  '/level': typeof LevelRoute
  '/play': typeof PlayRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/ramailo': typeof RamailoRoute
  '/random': typeof RandomRoute
  '/reminders': typeof RemindersRoute
  '/admin/cdc': typeof AdminCdcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/create': typeof CreateRoute
  '/learn': typeof LearnRoute
  '/level': typeof LevelRoute
  '/play': typeof PlayRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/ramailo': typeof RamailoRoute
  '/random': typeof RandomRoute
  '/reminders': typeof RemindersRoute
  '/admin/cdc': typeof AdminCdcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chapters'
    | '/create'
    | '/learn'
    | '/level'
    | '/play'
    | '/posts'
    | '/profile'
    | '/ramailo'
    | '/random'
    | '/reminders'
    | '/admin/cdc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chapters'
    | '/create'
    | '/learn'
    | '/level'
    | '/play'
    | '/posts'
    | '/profile'
    | '/ramailo'
    | '/random'
    | '/reminders'
    | '/admin/cdc'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chapters'
    | '/create'
    | '/learn'
    | '/level'
    | '/play'
    | '/posts'
    | '/profile'
    | '/ramailo'
    | '/random'
    | '/reminders'
    | '/admin/cdc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChaptersRoute: typeof ChaptersRoute
  CreateRoute: typeof CreateRoute
  LearnRoute: typeof LearnRoute
  LevelRoute: typeof LevelRoute
  PlayRoute: typeof PlayRoute
  PostsRoute: typeof PostsRoute
  ProfileRoute: typeof ProfileRoute
  RamailoRoute: typeof RamailoRoute
  RandomRoute: typeof RandomRoute
  RemindersRoute: typeof RemindersRoute
  AdminCdcRoute: typeof AdminCdcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ramailo': {
      id: '/ramailo'
      path: '/ramailo'
      fullPath: '/ramailo'
      preLoaderRoute: typeof RamailoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level': {
      id: '/level'
      path: '/level'
      fullPath: '/level'
      preLoaderRoute: typeof LevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cdc': {
      id: '/admin/cdc'
      path: '/admin/cdc'
      fullPath: '/admin/cdc'
      preLoaderRoute: typeof AdminCdcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChaptersRoute: ChaptersRoute,
  CreateRoute: CreateRoute,
  LearnRoute: LearnRoute,
  LevelRoute: LevelRoute,
  PlayRoute: PlayRoute,
  PostsRoute: PostsRoute,
  ProfileRoute: ProfileRoute,
  RamailoRoute: RamailoRoute,
  RandomRoute: RandomRoute,
  RemindersRoute: RemindersRoute,
  AdminCdcRoute: AdminCdcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
